_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 2
                - 3
                - 49
                - 55
            "2":
                - 2
                - 3
                - 49
                - 55
            "3":
                - 2
                - 16
                - 23
                - 24
                - 55
            "4": 3.12.7
            "5": 0.19.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
Learning_rate:
    value: 0.01
batch_size:
    value: 32
epochs:
    value: 50
layer_size:
    value:
        - 784
        - 128
        - 64
        - 10
