wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
beta:
  value: 0.9
beta1:
  value: 0.8
beta2:
  value: 0.999
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_size:
  value: 64
learning_rate:
  value: 0.0001
loss:
  value: cross_entropy
momentum:
  value: 0.9
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0
weight_init:
  value: random
