wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
beta:
  value: 0.8
beta1:
  value: 0.9
beta2:
  value: 0.999
epochs:
  value: 10
epsilon:
  value: 1.0e-08
hidden_size:
  value: 32
learning_rate:
  value: 0.0001
momentum:
  value: 0.9
num_layers:
  value: 5
optimizer:
  value: adam
weight_decay:
  value: 0.5
weight_init:
  value: random
