_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 2
                - 3
                - 49
                - 55
            "2":
                - 2
                - 3
                - 49
                - 55
            "3":
                - 16
                - 19
                - 23
                - 24
                - 55
            "4": 3.12.7
            "5": 0.19.8
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
Learning_rate:
    value: 0.01
activation_function:
    value: ReLu
batch_size:
    value: 32
beta_1:
    value: 0.9
beta_2:
    value: 0.999
epochs:
    value: 2
hidden_num:
    value: 2
hidden_size:
    value: 64
initialization:
    value: xavier
layer_size:
    value:
        - 784
        - 64
        - 64
        - 10
loss_function:
    value: categorical_cross_entropy
optimizer:
    value: NAG
weight_decay:
    value: 0
