_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 2
                - 3
                - 49
                - 55
            "2":
                - 2
                - 3
                - 49
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.7
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
activation:
    value: ReLU
batch_size:
    value: 32
beta:
    value: 0.9
beta1:
    value: 0.9
beta2:
    value: 0.999
dataset:
    value: fashion_mnist
epochs:
    value: 10
epsilon:
    value: 1e-08
hidden_size:
    value: 256
learning_rate:
    value: 0.001
loss:
    value: cross_entropy
momentum:
    value: 0.9
num_layers:
    value: 2
optimizer:
    value: adam
wandb_entity:
    value: da24s006-indian-institue-of-technology-madras-
wandb_project:
    value: experiment1
weight_decay:
    value: 0.001
weight_init:
    value: Xavier
