wandb_version: 1

Learning_rate:
  value: 0.0001
activation_function:
  value: ReLu
batch_size:
  value: 16
beta_1:
  value: 0.9
beta_2:
  value: 0.99
epochs:
  value: 10
hidden_num:
  value: 3
hidden_size:
  value: 64
initialization:
  value: random
loss_function:
  value: categorical_cross_entropy
optimizer:
  value: momentum sgd
weight_decay:
  value: 0.0005
