_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 2
                - 3
                - 49
                - 55
            "2":
                - 2
                - 3
                - 49
                - 55
            "3":
                - 2
                - 14
                - 17
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.8
            "8":
                - 1
                - 3
                - 5
            "12": 0.19.8
            "13": windows-amd64
Learning_rate:
    value: 0.0001
activation_function:
    value: Sigmoid
batch_size:
    value: 64
beta_1:
    value: 0.9
beta_2:
    value: 0.99
epochs:
    value: 10
hidden_num:
    value: 3
hidden_size:
    value: 128
initialization:
    value: xavier
loss_function:
    value: mean_squared
optimizer:
    value: Adam
weight_decay:
    value: 0
