wandb_version: 1

Learning_rate:
  value: 0.001
activation_function:
  value: ReLu
batch_size:
  value: 32
beta_1:
  value: 0.9
beta_2:
  value: 0.99
epochs:
  value: 5
hidden_num:
  value: 4
hidden_size:
  value: 64
initialization:
  value: random
loss_function:
  value: categorical_cross_entropy
optimizer:
  value: Adam
weight_decay:
  value: 0.0005
