wandb_version: 1

Learning_rate:
  value: 0.001
activation_function:
  value: Sigmoid
batch_size:
  value: 32
beta_1:
  value: 0.9
beta_2:
  value: 0.99
epochs:
  value: 10
hidden_num:
  value: 3
hidden_size:
  value: 64
initialization:
  value: random
loss_function:
  value: mean_squared
optimizer:
  value: NAG
weight_decay:
  value: 0.0005
